default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

pos_development:
  <<: *default
  database: pos_development

pos_test:
  <<: *default
  database: pos_test

production:
  url: <%= ENV['POS_DATABASE_URL'] %>

development:
  <<: *default
  database: bfc-members_development

test:
  <<: *default
  database: bfc-members_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
